-- DROP TABLE IF EXISTS "REPOSITORY"."PLUGIN";
-- DROP TABLE IF EXISTS "REPOSITORY"."CATEGORY";
-- DROP SCHEMA IF EXISTS "REPOSITORY";
CREATE SCHEMA "REPOSITORY"

--
-- Table structure for table "PLUGIN"
--
CREATE TABLE "REPOSITORY"."PLUGIN"
(
"PLUGIN_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(45) NOT NULL,
"BUILD" DATE,
"VERSION" VARCHAR(45) NOT NULL,
"DESCRIPTION" VARCHAR(255),
"COMPATIBLE_VERSION" VARCHAR(45) NOT NULL,
"OS" VARCHAR(45),
"ARCH" VARCHAR(45),
"DEPENDENCY" VARCHAR(255),
"CATEGORY_ID" VARCHAR(32),
"PUBLISHED" TINYINT DEFAULT 0,
"DELETED" TINYINT DEFAULT 0,
CLUSTER PRIMARY KEY("PLUGIN_ID"));

COMMENT ON TABLE "REPOSITORY"."PLUGIN" IS '插件';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."PLUGIN_ID" IS '插件ID';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."NAME" IS '插件名称';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."BUILD" IS '插件构建日期';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."VERSION" IS '插件版本号';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."DESCRIPTION" IS '插件描述';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."COMPATIBLE_VERSION" IS '插件前向兼容的最老版本';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."OS" IS '插件依赖的操作系统最低版本';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."ARCH" IS '插件处理器架构，分为x86,amd64,mips,aarch64等';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."DEPENDENCY" IS '插件所依赖的插件ID列表，以逗号分隔';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."CATEGORY_ID" IS '插件类别ID';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."PUBLISHED" IS '插件发布状态，0表示下架， 1表示发布';
COMMENT ON COLUMN "REPOSITORY"."PLUGIN"."DELETED" IS '插件删除状态, 0表示未删除， 1表示已放入回收站';

--
-- Table structure for table "CATEGORY"
--
CREATE TABLE "REPOSITORY"."CATEGORY"
(
"CATEGORY_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(45) NOT NULL,
"PARENT_ID" VARCHAR(32),
CLUSTER PRIMARY KEY("CATEGORY_ID"));

COMMENT ON COLUMN "REPOSITORY"."CATEGORY"."CATEGORY_ID" IS '类别ID';
COMMENT ON COLUMN "REPOSITORY"."CATEGORY"."NAME" IS '类别名称';