server:
  #http:
    #port: 48910
  port: 48911
  #ssl:
    #enabled: true
    #key-alias: server
    #key-store-password: 123456
    #key-store: file:///${GTCLOUD_SYSDATA_DIR}/config/ssl-cert/server.p12
    #key-store-type: PKCS12

spring:
  application:
    name: PluginRepositoryGatewayApp
  main:
    banner-mode: "off"
  cloud:
    gateway:
      filter:
        remove-hop-by-hop:
          headers:
            - Connection
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: "true"
      default-filters:
        - RemoveRequestHeader=Expect
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      routes:
        - id: plugin-repository
          uri: http://127.0.0.1:39234
          predicates:
            - Path=/repository/**
